removed core/ from embed

diff --git a/core/tpl/clog.yaml b/core/tpl/clog.yaml
--- a/core/tpl/clog.yaml
+++ b/core/tpl/clog.yaml
@@ -1,5 +1,3 @@
----
-# yamllint disable rule:colons
 #        _                                                 _
 #   __  | |  ___   __ _   ___   ___  __ _   _ __    _ __  | |  ___
 #  / _| | | / _ \ / _` | |___| (_-< / _` | | '  \  | '_ \ | | / -_)
@@ -7,7 +5,7 @@
 #                 |___/                            |_|
 # Values in this file are specific to building your project
 #
-# use  `clog Core Init`   to copy the core init into folder clogrc
+# use  `clog Init`   to copy the core init into folder clogrc
 #                      ⇓⇓⇓⇓⇓⇓⇓⇓⇓
 # ALL KEYS ARE    ⇒⇒  lowercase    ⇐⇐  only. THIS IS A VIPER SETTING.
 #                      ⇑⇑⇑⇑⇑⇑⇑⇑⇑
@@ -30,23 +28,35 @@ clog:
 #   ||             |_|    |_|
 # -----------------------------------------------------------------------------
 snippets:
+  # build control logic for this repo - all commands start with bc
+  bc-releases-yaml: yq -r '.clog."releases-path"' clogrc/clog.yaml
   git:
     tag:
-      ref: echo "v$(yq -r '.[0].version' releases.yaml)" #add a v for golang
+      ref: echo "v$(yq -r '.[0].version'"$(clog bc-releases-yaml)")" #add a v for golang
+      # a go package needs a preceding "v"
+      refgo: echo "v$(clog git tag ref)"
     message:
-      ref: yq -r '.[0].note' releases.yaml
-    suffix: b="$(git branch --show-current)";[[ "$b" == main ]]&&echo ""|||tr -d [:blank:]
+      ref: yq -r '.[0].note'"$(clog bc-releases-yaml)"
+  suffix: |
+    b="$(git branch --show-current)"
+    [[ "$b" == main ]] && echo "" || echo "$b"|tr -d '[:blank:]'
   project:
     config: |
       # make some variables for standard build scripts
-      export PROJECT=clog                            # project you're building
+      export PROJECT="$(basename $(pwd))"           # project you're building
     needs:
       # grab the golang version from go.mod
       golang: cat go.mod|grep '^go '|grep -oE '[0-9]\.[0-9]+\.[0-9]+'
-  argstest: |
-    echo "MAKE=($1) ($2) ($3) ($4)"
-    echo "Another line"
-    echo "$1 is still one"
+      # hunt for the hugo version
+      hugo: |
+        # grab the version from configuration
+        if [ -f hugo .yaml ];then
+          yq -r '.module.hugoVersion.min' hugo.yaml
+        elif [ -f config/_default/module.yaml ];then
+          yq -r '.hugoVersion.min' config/_default/module.yaml
+        else
+          echo "hugo config not found"
+        fi
 # #############################################################################
 #        _                   ___   _                 _
 #   __  | |  ___   __ _     / __| | |_    ___   __  | |__
@@ -61,23 +71,3 @@ check:
           vgo="$(go version|cat go.mod|grep '^go '|grep -oE '[0-9]\.[0-9]+\.[0-9]+')" 
           [[ "$vgo" == "$(clog project needs golang)" ]]
         catch: clog Log -E "wrong go version. Need $(clog project needs golang)"
-  build:
-    blocks:
-      - try: go test
-        catch: clog Log -E "go test failed"
-  # --- clog Check deploy -----------------------------------------------------
-  aws-deploy:
-    blocks:
-      # beware the first block needs double quotes or it becomes an array!
-      - try: "[ -n \"$CLOG_BUCKET\" ]"
-        ok: clog Log -I "\$CLOG_BUCKET ok"
-        catch: clog Log -E "\$CLOG_BUCKET not set - cannot deploy"
-      - try: aws --version 2>/dev/null| grep aws-cli/2. | head -c 10
-        ok: clog Log -I "aws cli v2 ok"
-        catch: clog Log -E "aws cli v2 not installed - try clog install aws"
-      - try: aws s3 cp --dryrun LICENSE $CLOG_BUCKET/LICENSE
-        ok: clog Log -I "aws s3 write access to bucket ok"
-        catch: clog Log -E "aws s3 cli - cannot write to \$CLOG_BUCKET/LICENSE"
-      - try: go test
-        ok: clog Log -I "go test passed"
-        catch: clog Log -E "go test failed"
