clog Aws Dns

diff --git a/core/core.clog.yaml b/core/core.clog.yaml
--- a/core/core.clog.yaml
+++ b/core/core.clog.yaml
@@ -126,6 +126,172 @@ check:
 #   ||             |_|    |_|
 # -----------------------------------------------------------------------------
 snippets:
+  #        _         
+  #   ||_ | |__   __ 
+  #  (_-< | '_ \ / _|
+  #  / _/ |_.__/ \__|
+  #   ||             
+  bc-releases-yaml: yq -r '.clog."releases-path"' clogrc/clog.yaml
+  bc-main-repo: echo "metarex-media/www-metarex-media"
+  bc-prod-version: yq -r 'first(.[] | select(.build=="prod" and .type=="main") | .version)' "$(clog bc-releases-yaml)"
+  bc-prod-logic-build: |
+    do="$(yq -r '.[0].build|select(.=="prod")' "$(clog bc-releases-yaml)")"
+    [ -z "$do" ] && do="dev(from releases.yaml)" || do="prod(from releases.yaml)" 
+    # rules - ensure valid branch for workflow
+    [[ "create" == "$GITHUB_EVENT_NAME " ]] && git checkout main
+    # overrides always win - prod override strongest
+    clog Should MAKE "dev" && do="dev(forced by MAKE)"
+    clog Should MAKE "prod" && do="prod(forced by MAKE)"
+    echo "$do"
+  bc-prod-logic-deploy: |
+    do="$(yq -r '.[0].build|select(.=="prod")' "$(clog bc-releases-yaml)")"
+    [ -z "$do" ] && do="dev(from releases.yaml)" || do="prod(from releases.yaml)" 
+    # rules
+    [[ "create" == "$GITHUB_EVENT_NAME " ]] && git checkout main
+    [ -n "$(clog git branch)" ] && [[ "$(clog git branch)" != "main" ]] && do="dev(not main branch)"
+    [[ "$(clog bc-main-repo)" != "$(clog git repo)" ]] && do="dev(repo!=$(clog bc-main-repo))"
+    # overrides always win - prod override strongest
+    clog Should MAKE "dev" && do="dev(forced by MAKE)"
+    clog Should MAKE "prod" && do="prod(forced by MAKE)"
+    echo "$do"
+  bc-wants-stage-flow:  yq -r '.[0].flow|select(.=="stage")' "$(clog bc-releases-yaml)"
+  bc-wants-test-flow:  yq -r '.[0].flow|select(.=="test")' "$(clog bc-releases-yaml)"
+  bc-message-file: echo "tmp/workflow-message"
+  bc-log-divider: eval "$(clog Crayon)";for i in {1..8};do HR="$HR\e[09${i}m▬▬▬▬▬▬▬▬▬$cE|";done;printf "$HR$cX\n"
+  # worker function instagram ----------------------------------------------------------------------------------------
+  bc-instagram: |
+    eval "$(clog Crayon)" # setting & highlights
+    clog Log -W  "    ✖️ $cC clog instagram$cI $*$cX not implemented yet - come back later"
+    exit 0
+  # worker function main - for websites ------------------------------------------------------------------------------
+  bc-main: |
+    eval "$(clog Source project config); $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+    vMain="$(clog bc-prod-version)"
+
+    ERR=0
+    clog Log -I "$STEP.$(((++s))).⚒️  bc-main-website  $modeMSG→$cF setup queries for daily build/"
+    [ -z "vMain" ]&&clog Log -E "releases.yaml has no entry with type=main build=prod"&&exit (((++ERR)))
+    git checkout "vMain"
+    [ $? -gt 0 ]&&clog Log -E "cannot checkout to tag $cE$vMain"&&exit (((++ERR)))
+
+    # we are now checked out to the production snapshot $vMain
+    # releases.yaml and scripts
+    clog instagram fetch metarex latest tmp/insta-mrx
+  # worker function hugo ---------------------------------------------------------------------------------------------
+  bc-hugo: |
+    eval "$(clog Source project config); $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+
+    ERR=0
+    clog Log -I "$STEP.$(((++s))).⚒️  build hugo  $modeMSG→$cF kodata/"
+
+    [ ! -d content ] && clog Log -E "$STEP.$(((++s))). no content/ folder" && exit 1
+    clog Log -I "$STEP.$(((++s))). purge$cF kodata/$cX, build site"
+    rm -rf kodata/*
+
+    opt="";[ -z "$doPROD" ]  && opt="$opt --buildDrafts --buildFuture --buildExpired"
+    clog Log -I "$STEP.$(((++s))). build hugo $modeMSG→${cF}kodata/$cC $opt"
+    hugo build --minify --logLevel info $opt
+  # worker function golang -------------------------------------------------------------------------------------------
+  #  $EXE   is the executable name - overrides the default of $PROJECT
+  #  $TITLE is the title string for semver
+  #  artifacts appear in tmp/
+  #  you may have to make a project copy of this function to make semver work
+  bc-golang: |
+    eval "$(clog Source project config); $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+    [ -z "$EXE" ] && EXE="$PROJECT"
+    ERR=0
+    help="tpl/help-golang.sh"    # build helpers
+    eval "$(clog Cat $help)"
+
+    clog Log -I "$STEP.$(((++s))).⚒️  build $EXE $modeMSG→$cF tmp/$EXE-cpu-os"
+
+    # ensure tmp folder exists
+    mkdir -p tmp
+    branch="$(clog git branch)"
+    hash="$(clog git hash head)"                                # use the head hash as the build hash
+    suffix="" && [[ "$branch" != "main" ]] && suffix="$branch"  # use the branch name as the suffix
+    app="$EXE"                                                  # command you type to run the build
+    title="$TITLE"                                              # title of the software
+    linkerPath="github.com/mrmxf/$EXE/semver.SemVerInfo"        # go tool objdump -S $EXE|grep /semver.SemVerInfo
+
+      fGoBuild tmp/$app-amd-lnx     linux   amd64 $hash "$suffix" $app "$title" "$linkerPath"; ((ERR+=$?))
+    # fGoBuild tmp/$app-amd-win.exe windows amd64 $hash "$suffix" $app "$title" "$linkerPath"; ((ERR+=$?))
+      fGoBuild tmp/$app-amd-mac     darwin  amd64 $hash "$suffix" $app "$title" "$linkerPath"; ((ERR+=$?))
+      fGoBuild tmp/$app-arm-lnx     linux   arm64 $hash "$suffix" $app "$title" "$linkerPath"; ((ERR+=$?))
+    # fGoBuild tmp/$app-arm-win.exe windows arm64 $hash "$suffix" $app "$title" "$linkerPath"; ((ERR+=$?))
+      fGoBuild tmp/$app-arm-mac     darwin  arm64 $hash "$suffix" $app "$title" "$linkerPath"; ((ERR+=$?))
+    clog Log -B "$ERR" "$doPROD" "✅ bc-golang $modeMSG→$cS tmp/$cX ok" "❌ bc-golang  $modeMSG→$cE tmp/$cX failed" || exit 1; #abort if PROD
+  # worker function ko -----------------------------------------------------------------------------------------------
+  bc-ko: |
+    eval "$(clog Source project config); $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+
+    ERR=0
+    clog Log -I "$STEP.$(((++s))).⚒️  build ko $modeMSG→$cU hub.docker.com/$DOCKER_NS$cX"
+
+    [ -z "$doPROD" ] && devTAG="-dev"
+    [ -n "$(clog bc-wants-stage-flow)" ]&& stageTAG="-stage"
+    
+    tag1="$(clog git tag ref)$devTAG" # 1.2.3 | 1.2.3-stage | 1.2.3-stage-dev
+    tag2="latest$stageTAG$devTAG"     # latest | latest-stage | latest-dev | latest-stage-dev
+
+    # config is in .ko.yaml
+    # use the default docker repo unless told otherwise
+    [ -z "$KO_DOCKER_REPO" ] && KO_DOCKER_REPO="$DOCKER_NS"
+    export KO_DOCKER_REPO                                      # push to repo
+    export KO_CONFIG_PATH=".ko.yaml"                           # build options
+    export KO_DATA_DATE_EPOCH=$(git log -1 --format='%ct')     # date on image
+
+    ko build --base-import-paths --tags "$tag1" --tags "$tag2" .
+    if [ $? -gt 0 ]; then
+      msg="ko build failed $cE $PROJECT$cX:$cW$tag1$cX and ${cW}$tag2"
+      clog Log -E "$msg"
+      printf "$msg" > /tmp/clog-notify
+      exit 1
+    fi
+    msg="multi-arch ko build$cF $PROJECT$cX:$cW$tag1$cX and ${cW}$tag2"
+    clog Log -S "$msg"
+    printf "$msg" > /tmp/clog-notify
+  # worker function flowx ----------------------------------------------------------------------------------------------
+  # this is the core, generic flow script - it never appears in MAKE
+  # $VERB is the title for display
+  # $CHK & $MAKE contain tokens that clog perform
+  #   check:  clog Check $TOK
+  #   build:  clog bc-$TOK
+  bc-flowx: |
+    cTOKs=($CHK)
+    mTOKs=($MAKE)
+
+    modeMSG="$(clog bc-prod-logic-build)"
+    [[ "${modeMSG:0:4}" == "prod" ]] && doPROD="prod"
+
+    eval "$(clog Source project config); $(clog Crayon)"  # setting & highlight
+    clog Log -I  "🤖 $VERB $modeMSG$cS $PROJECT$cX MAKE ${#mTOKs[@]} steps:$cC ${mTOKs[@]}"
+
+    ERR=0; export STEP=0
+
+    for TOK in "${cTOKs[@]}"; do
+      clog Log -I "$(((++STEP))).  Check $TOK"; clog Check "$TOK"; ERR=$((ERR+$?))
+    done
+
+    clog bc-log-divider
+
+    for TOK in "${mTOKs[@]}"; do
+      ((STEP++));clog bc-"$TOK" "$doPROD" "$modeMSG" && clog bc-log-divider
+    done
+
+    icon="✅";[ $ERR -gt 0 ] && icon="❌"
+    printf -v MSG "$icon $VERB $modeMSG complete with %d errors" $ERR
+    echo "$modeMSG" > "$(clog bc-message-file)"
+    clog Log -B "$ERR" "$doPROD" "✅ bc-flowx ok - $modeMSG" "❌ bc-flowx failed - $modeMSG" || exit 1; #abort if PROD
+    exit 0
   #             _
   #   ||_    __| |  ___  __ __
   #  (_-<   / _` | / -_) \ V /
@@ -260,7 +426,7 @@ snippets:
       # Add Docker's official GPG key:
       sudo apt-get -qq update; sudo apt-get -qq upgrade
       sudo apt-get install -yq ca-certificates curl
-      sudo install -q -m 0755 -d /etc/apt/keyrings
+      sudo install -m 0755 -d /etc/apt/keyrings
       sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
       sudo chmod a+r /etc/apt/keyrings/docker.asc
       # Add the repository to Apt sources:
@@ -293,6 +459,15 @@ snippets:
       && sudo apt install gh -y
     gh-mac: brew install gh
     git: sudo apt-get install -y git-all
+    helm: |
+      # tbd mac brew install helm
+      curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
+      sudo apt-get install apt-transport-https --yes
+      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
+      sudo apt-get update
+      sudo apt-get install helm
+      helm version --template='Version: {{.Version}}' && exit 0
+      exit 1
     homebrew: |
       [[ "$(uname -m)" == "arm64" ]] && clog Log -W "arm is badly supported!"
       sudo apt-get install -y build-essential procps curl file git
@@ -386,6 +561,21 @@ snippets:
       curl -sSfL "$url" > "$TMP"
       sudo mv "$TMP" "$DST" && sudo chmod +x "$DST"
     snap: sudo apt install -y snapd
+    terraform: |
+      #tbd mac - brew tap hashicorp/tap
+      #tbd brew install hashicorp/tap/terraform
+      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
+      wget -O- https://apt.releases.hashicorp.com/gpg | \
+      gpg --dearmor | \
+      sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
+      # verify the gpg key:
+      gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
+      # add the official Hashicorp repo
+      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+      sudo apt-get update
+      sudo apt-get install terraform
+      terraform -version && exit 0
+      exit 1
     yarn: npm install --global yarn && echo "PATH=\"$PATH:$(yarn global bin)\"" >> ~/.bashrc
     yq: |
       arch="arm64" ; [[ "$(uname -m)" == "x86_64" ]] && arch="amd64"
